version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  disburser:
    build: .
    command: bundle exec rails s -p 3000
    volumes:
      - .:/app
      - bundle_gems:/usr/local/bundle
    ports:
      - "${DISBURSER_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - sidekiq
    tmpfs:
      - /opt/app/tmp
  
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    links:
      - postgres
      - redis
    env_file:
      - .env
    command: bundle exec sidekiq

  redis:
    image: redis
    

volumes:
  postgres_data:
  bundle_gems:
